platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YBLiveOne' do
  pod 'SDWebImage','5.2.5'
  pod 'Masonry', '1.0.2'
  pod 'JKCategories','1.9.3'
  pod 'DZNEmptyDataSet','1.8.1'
  pod 'PrintBeautifulLog','1.2.0'
  pod 'TYPagerController','2.1.2'
  # bugly
  pod 'Bugly', '~> 2.4.6'
  # 网络请求
  pod 'MJRefresh','3.2.0'
  pod 'AFNetworking','4.0.1'
  #socket
  pod 'Socket.IO-Client-Swift','15.1.0'
  
  # 分享
  pod 'mob_sharesdk','4.4.34'
  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
  #pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'   #（微信sdk不带支付的命令）
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' #（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
  pod 'mob_sharesdk/ShareSDKPlatforms/Apple' #苹果登录
  
  # 支付宝
  pod 'AliPay','15.7.4.2'
  pod 'OpenSSL-for-iOS', '1.0.2.d.1'
  #  SVGAPlayer
  pod 'SVGAPlayer','2.3.5'
  #  弹窗
  pod 'CWStatusBarNotification', '~> 2.3.5'
  #  YYImage用来加载gif
  pod 'YYWebImage','1.0.5'
  pod 'YYText','1.0.7'
  
  #  #键盘管理
  pod 'IQKeyboardManager',"6.2.0"
  #  轮播图
  pod 'SDCycleScrollView','1.82'
  #  提示语展示框
  pod 'MBProgressHUD','1.1.0'
  #  应用内推送展示
  #  pod 'EBBannerView'
  #   pod 'TXIMSDK_TUIKit_iOS'
  #  腾讯全功能专业版SDK
  pod 'TXLiteAVSDK_Professional','10.9.13148'
  
  #  腾讯IM
  pod 'TXIMSDK_Plus_iOS', '7.0.3754'
  
  
  #腾讯上传
  pod 'QCloudCOSXML','5.7.4'
  pod 'JPVideoPlayer','3.1.1'
  
  pod 'ZFPlayer','4.1.4'
  pod 'ZFPlayer/ControlView'
  pod 'ZFPlayer/ijkplayer'
  pod 'ZFPlayer/AVPlayer'
  
  pod 'lottie-ios', '~> 2.5.0'
  pod 'TZImagePickerController','3.8.7'
  #七牛
  pod 'Qiniu','7.4.3'
  #AT 功能
  pod 'HPGrowingTextView','1.1'
  pod 'FreeStreamer', '~> 3.8.2'
  #PayPal
  pod 'Braintree'
  #AWS
  pod 'AWSS3','2.19.1'
  #openinstall
  pod 'libOpenInstallSDK','2.8.3'
  

  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end
end
